### ISSUE TITLE
Break Signature Validation

### ISSUE THREAD

**Issue by DaKnOb** [grnet/zeus#30]
All voters receive via e-mail a receipt that they have voted on the system.
This receipt contains a line starting by `CANDIDATES` that has all available options, comma or `%` separated. Each new line is represented by a `{newline}` word. If the question name contains a `,` (comma), or a `%`, it will break the spacing inside the receipt making it difficult to be decoded and may fail automated receipt validation techniques.

**Comment by ergonomicon** [comment]
Signatures in receipts will not break because they are always automatically validated before sending them out. However, if the front-end does not stop invalid input early, the election will not be able to register votes due to validation failure. Comma poses no problem, but `%` does and it will be fixed. Thanks.
